service: psnaks-serverless

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 30
  httpApi:
    cors: false

functions:
  api:
    handler: src.main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

# plugins:
#   - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: false
    useStaticCache: false
    # slim: true
    # zip: true

package:
  exclude:
    - venv/**
    - node_modules/**
    - .serverless/**